version: '0.1'

services:
  question-service:
    build: 
      context: ./service/question-service
      args:
        - PORT=${QUESTION_PORT}
    ports:
      - "${QUESTION_PORT}:${QUESTION_PORT}"
    environment:
      PORT: ${QUESTION_PORT}
      DB_CLOUD_URI: ${QUESTION_DB_CLOUD_URI}     
      DB_LOCAL_URI: ${QUESTION_DB_LOCAL_URI}    
      ENV: ${ENV}                        
    depends_on:
      - question-db

  question-db:
    image: mongodb/mongodb-atlas-local
    ports:
      - "27018:27018"

  user-service:
    build: 
        context: ./services/user-service
        args:
          - PORT=${USER_PORT}
    ports:
      - "${USER_PORT}:${USER_PORT}"
    environment:
      PORT: ${USER_PORT}
      DB_CLOUD_URI: ${USER_DB_CLOUD_URI}     
      DB_LOCAL_URI: ${USER_DB_LOCAL_URI}    
      ENV: ${ENV}                        
    depends_on:
      - user-db

  user-db:
    image: mongodb/mongodb-atlas-local
    ports:
      - "27019:27019"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" 
    depends_on:
      - user-service
      - question-service