version: '0.1'

services:
  question-service:
    build: 
      context: ./services/question-service
      args:
        - PORT=${QUESTION_PORT}
    ports:
      - "${QUESTION_PORT}:${QUESTION_PORT}"
    environment:
      PORT: ${QUESTION_PORT}
      DB_CLOUD_URI: ${QUESTION_DB_CLOUD_URI}     
      DB_LOCAL_URI: ${QUESTION_DB_LOCAL_URI}    
      ENV: ${ENV}                     
    depends_on:
      - question-db

  question-db:
    image: mongodb/mongodb-atlas-local
    ports:
      - "27018:27018"

  user-service:
    build: 
        context: ./services/user-service
        args:
          - PORT=${USER_PORT}
    ports:
      - "${USER_PORT}:${USER_PORT}"
    environment:
      PORT: ${USER_PORT}
      DB_CLOUD_URI: ${USER_DB_CLOUD_URI}     
      DB_LOCAL_URI: ${USER_DB_LOCAL_URI}    
      ENV: ${ENV}       
      JWT_SECRET: ${JWT_SECRET}                   
    depends_on:
      - user-db

  user-db:
    image: mongodb/mongodb-atlas-local
    ports:
      - "27019:27019"

  matching-service:
    build: 
        context: ./services/matching-service
        args:
        - PORT=${MATCHING_PORT}
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    ports:
      - "${MATCHING_PORT}:${MATCHING_PORT}"
    environment:
      PORT: ${MATCHING_PORT}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ENV: ${ENV}
    depends_on:
      - redis

  collaboration-service:
    build: 
        context: ./services/collaboration-service
        args:
        - PORT=${COLLAB_PORT}
    ports:
      - "${COLLAB_PORT}:${COLLAB_PORT}"
    environment:
      PORT: ${COLLAB_PORT}
      ENV: ${ENV}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    depends_on:
      - user-service
      - question-service
      - matching-service

  