apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP  # Use LoadBalancer for external access (with `minikube tunnel`)
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: user-service
