apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - name: collaboration-service
        image: wuemily/collaboration-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: ENV
          value: "${ENV}"
